# Artifact Hub repository metadata file
# https://artifacthub.io/docs/topics/repositories/

repositoryID: 2a1be652-53bf-42c6-a2b5-7b87f26bc585
displayName: Traktor Operator
owners:
  - name: GDX Cloud
    email: support@gdxcloud.net
