apiVersion: traktor.gdxcloud.net/v1alpha1
kind: SecretsRefresh
metadata:
  labels:
    app.kubernetes.io/name: traktor
    app.kubernetes.io/managed-by: kustomize
  name: secretsrefresh-simple
spec:
  # Watch all namespaces with label 'watch-secrets: true'
  namespaceSelector:
    matchLabels:
      watch-secrets: "true"
  
  # Watch all secrets with label 'refresh: enabled'
  secretSelector:
    matchLabels:
      refresh: "enabled"
  
  refreshInterval: "10m"
