apiVersion: traktor.gdxcloud.net/v1alpha1
kind: SecretsRefresh
metadata:
  labels:
    app.kubernetes.io/name: traktor
    app.kubernetes.io/managed-by: kustomize
  name: secretsrefresh-gdx
  namespace: traktor-system
spec:
  # Filter namespaces by labels
  namespaceSelector:
    matchLabels:
      name: "dev-sergei-baikin"

  # Filter secrets by labels within matched namespaces
  secretSelector:
    matchLabels:
      traktor: "true"
